name: media_downloader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-327.3.beta

dependencies:
  dio: ^5.11.1
  ffmpeg_kit_flutter_new: ^4.6.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  font_awesome_flutter: ^11.0.0
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  web: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/asset/instagram.png
    - lib/asset/facebook.png
    - lib/asset/tiktok.png
    - lib/asset/youtube.png
    - lib/asset/1.png
